name: Prepare a PR for WINGET due a new version of squidowl/halloy

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow run sync-fork_winget-pkgs.yml
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_RUN_TOKEN }}

      - name: HALLOY_RELEASE
        shell: bash
        run: |
          echo "HALLOY_RELEASE=$(gh release view -R squidowl/halloy --json name,publishedAt,body,assets)" >> $GITHUB_ENV

      - name: HALLOY_VERSION
        shell: bash
        run: |
          echo "HALLOY_VERSION=$(echo $HALLOY_RELEASE | jq .name -r)" >> $GITHUB_ENV

      - name: HALLOY_PUBLISHED_AT
          echo "HALLOY_PUBLISHED_AT=$(echo $HALLOY_RELEASE | jq .publishedAt -r)" >> $GITHUB_ENV

      - name: HALLOY_RELEASE_NOTES
          echo "HALLOY_RELEASE_NOTES=$(echo $HALLOY_RELEASE | jq .body -r)" >> $GITHUB_ENV

      - name: HALLOY_BINARY_SHA256
          echo "HALLOY_RELEASE_NOTES=$(echo $HALLOY_RELEASE | jq .body -r)" >> $GITHUB_ENV

      - name: Get binary hash
      - name: Clone KaiKorla\winget-pkgs
        shell: bash
        run: |
      - name: Create branch
      - name: Take templates and replace valus
