name: Sync squidowl/halloy

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo sync KaiKorla/halloy -b main
        env:
          GH_TOKEN: ${{ secrets.GH_SYNC_TOKEN }}
