name: Sync microsoft/winget-pkgs

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo sync KaiKorla/winget-pkgs -b master
        env:
          GH_TOKEN: ${{ secrets.GH_SYNC_TOKEN }}
